-- MySQL Script generated by MySQL Workbench
-- Sat Muserar  5 15:18:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GamingArchives
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GamingArchives
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GamingArchives` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mavenmoviesmini_normalized
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mavenmoviesmini_normalized
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mavenmoviesmini_normalized` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `GamingArchives` ;

-- -----------------------------------------------------
-- Table `GamingArchives`.`user_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GamingArchives`.`user_record` ;

CREATE TABLE IF NOT EXISTS `GamingArchives`.`user_record` (
  `record_id` INT NOT NULL,
  `student_name` VARCHAR(45) NOT NULL,
  `age` INT(2) NULL,
  `birthday` DATE NULL,
  `sex` ENUM('male', 'female') NULL,
  `student_course` VARCHAR(45) NULL,
  `student_number` INT(10) NULL,
  `favorite_game` VARCHAR(45) NULL,
  `contact_number` VARCHAR(45) NULL,
  `personal_address` TINYTEXT NULL,
  `email_address` VARCHAR(45) NULL,
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `record_id_UNIQUE` (`record_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GamingArchives`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GamingArchives`.`user` ;

CREATE TABLE IF NOT EXISTS `GamingArchives`.`user` (
  `role` ENUM('admin', 'member', 'guest') NULL,
  `record_id` INT NOT NULL,
  INDEX `record_id_idx` (`record_id` ASC) ,
  CONSTRAINT `record_id`
    FOREIGN KEY (`record_id`)
    REFERENCES `GamingArchives`.`user_record` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GamingArchives`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GamingArchives`.`member` ;

CREATE TABLE IF NOT EXISTS `GamingArchives`.`member` (
  `record_id` INT NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `password` TINYTEXT NOT NULL,
  `membercol` VARCHAR(45) NULL,
  INDEX `record_id_idx` (`record_id` ASC) ,
    FOREIGN KEY (`record_id`)
    REFERENCES `GamingArchives`.`user_record` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GamingArchives`.`event_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GamingArchives`.`event_record` ;

CREATE TABLE IF NOT EXISTS `GamingArchives`.`event_record` (
  `idevent_record` INT NOT NULL,
  `event_name` VARCHAR(45) NULL,
  `event_description` MEDIUMTEXT NULL,
  `event_date` DATE NULL,
  PRIMARY KEY (`idevent_record`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GamingArchives`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GamingArchives`.`admin` ;

CREATE TABLE IF NOT EXISTS `GamingArchives`.`admin` (
  `record_id` INT NOT NULL,
  `position` VARCHAR(45) NULL,
  INDEX `record_id_idx` (`record_id` ASC) ,
    FOREIGN KEY (`record_id`)
    REFERENCES `GamingArchives`.`user_record` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
